# Generated by Django 3.2.10 on 2023-03-07 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999999999999)], verbose_name='Расчётный счёт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bik',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='БИК'),
        ),
    ]
