# Generated by Django 3.2.10 on 2023-03-13 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город нахождения компании')),
                ('postcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='Почтовый индес')),
                ('region', models.CharField(blank=True, max_length=120, null=True, verbose_name='Субъект РФ')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район города')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house_number', models.PositiveIntegerField(verbose_name='Номер дома')),
                ('is_legal', models.BooleanField(default=False, verbose_name='Юридический адрес компании')),
            ],
        ),
        migrations.RemoveField(
            model_name='branches',
            name='city',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='street',
        ),
        migrations.RemoveField(
            model_name='company',
            name='area',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='legal_address',
        ),
        migrations.DeleteModel(
            name='LegalAddress',
        ),
        migrations.AddField(
            model_name='branches',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo_handbook.companyaddress', verbose_name='Aдресс'),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='geo_handbook.companyaddress', verbose_name='Место'),
        ),
    ]