# Generated by Django 3.2.10 on 2023-03-06 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0002_auto_20230306_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='ИНН'),
        ),
    ]
