# Generated by Django 3.2.10 on 2023-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0002_auto_20230313_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='sro',
            name='number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Номер СРО'),
        ),
        migrations.AddField(
            model_name='sro',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название СРО сокращенное'),
        ),
    ]
