# Generated by Django 3.2.10 on 2023-03-06 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0003_alter_company_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)], verbose_name='ОГРН/ОГРНИП'),
        ),
    ]
