# Generated by Django 3.2.10 on 2023-03-17 06:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0004_auto_20230316_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=17, validators=[django.core.validators.MinValueValidator(17)], verbose_name='Кадастровый номер')),
                ('street', models.CharField(max_length=250, verbose_name='Улица')),
                ('house_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер дома')),
                ('building', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Строение/Корпус')),
                ('square', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь участка')),
                ('length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина')),
                ('title', models.TextField(verbose_name='Навзание объекта')),
                ('status', models.CharField(blank=True, choices=[('processed', 'Обработанная'), ('not processed', 'Не обработанная')], max_length=100, verbose_name='Статус заказа')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='geo_handbook.city', verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='geo_handbook.region', verbose_name='Регион')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='geo_handbook.typework', verbose_name='Тип работы')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='geo_handbook.order', verbose_name='Заказы')),
            ],
        ),
    ]
