# Generated by Django 3.2.10 on 2023-03-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0004_alter_company_ogrn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sro',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sro',
            name='number',
        ),
        migrations.AddField(
            model_name='company',
            name='sro_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма в члены СРО'),
        ),
        migrations.AddField(
            model_name='company',
            name='sro_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер решения о приёме в члены СРО'),
        ),
    ]
