# Generated by Django 3.2.10 on 2023-03-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0005_auto_20230309_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyspecialization',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='geo_handbook.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyspecialization',
            name='type_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_types', to='geo_handbook.typework', verbose_name='Тип работ'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='full_name',
            field=models.CharField(max_length=500, verbose_name='Название СРО'),
        ),
    ]
