# Generated by Django 3.2.10 on 2023-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0005_order_orderfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=150, verbose_name='Область/Район/Округ'),
        ),
    ]
