# Generated by Django 3.2.10 on 2023-03-17 07:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0006_order_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта заказчика'),
        ),
        migrations.AddField(
            model_name='order',
            name='father_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Отчество заказчика'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя заказчика'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=250, verbose_name='Фамилия заказчика'),
        ),
    ]
