# Generated by Django 3.2.10 on 2023-03-17 08:44

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0008_auto_20230317_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_handbook.area'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='area', chained_model_field='area', on_delete=django.db.models.deletion.CASCADE, to='geo_handbook.city'),
        ),
    ]
