# Generated by Django 3.2.10 on 2023-03-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0009_auto_20230317_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='height',
            new_name='heigth',
        ),
        migrations.AlterField(
            model_name='order',
            name='cadastral_number',
            field=models.CharField(max_length=50, verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('processed', 'Обработанная'), ('not processed', 'Не обработанная')], default='not processed', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='geo_handbook.typework', verbose_name='Тип работы'),
        ),
    ]
