# Generated by Django 3.2.10 on 2023-03-18 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0009_auto_20230317_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_region', models.CharField(max_length=50, verbose_name='регион работ')),
            ],
            options={
                'verbose_name': 'Регион работ',
                'verbose_name_plural': 'Регионы работ',
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название района'),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='postcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Название региона'),
        ),
        migrations.CreateModel(
            name='CompanyWorkRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_regions_companies', to='geo_handbook.company', verbose_name='Компания')),
                ('working_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_work_regions', to='geo_handbook.workregion', verbose_name='Регион выполняемых работ')),
            ],
            options={
                'verbose_name': 'Регион работ компаний',
                'verbose_name_plural': 'Регионы работ компаний',
            },
        ),
    ]
