# Generated by Django 3.2.10 on 2023-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_handbook', '0010_auto_20230318_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workregion',
            name='work_region',
        ),
        migrations.AddField(
            model_name='workregion',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='название субъекта'),
            preserve_default=False,
        ),
    ]
